### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#18]
- Delete yarn.lock
- Run `yarn`
- Commit yarn.lock
- Create pull request

**Comment by ceafive** [comment]
Hello, can you please assign this to me.

**Comment by arshadkazmi42** [comment]
Go ahead. Create a PR

**Comment by cicomsa** [comment]
Hello, I made a PR for this issue. I hope it helps.
