### ISSUE TITLE
Add http regex constants

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#3]
Add http regex
`'https?://github.com/'`

as constant in `constants/path.js`

**Comment by michaelymo** [comment]
I think the constant name is `HTTP_OR_HTTPS_PATH`.
Is this OK?

**Comment by arshadkazmi42** [comment]
How about keeping it `HTTP_REGEX_PATH`?

**Comment by michaelymo** [comment]
Nice! I got it.
