### ISSUE TITLE
Remove donation badges from README

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#32]
Remove `Buy me a Coffee` and `Become Patron` badge with the donation text from README.md

**Comment by thisShouldNotBeWorking** [comment]
Can I work on this issue as well?

**Comment by arshadkazmi42** [comment]
Sure go ahead

**Comment by thisShouldNotBeWorking** [comment]
![image](https://user-images.githubusercontent.com/82517773/180166039-12336b8e-c9a7-4c3c-bf72-bb6dabfdf388.png)
I need to remove these 3 things right?

**Comment by arshadkazmi42** [comment]
Yes

**Comment by arshadkazmi42** [comment]
@con-artist This is already fixed in a different PR. Just now checked it
