### ISSUE TITLE
License Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#6]
Add it with other badges in readme

```
[![LICENSE](https://img.shields.io/npm/l/@gh-conf/gh-conf-constants.svg)](https://github.com/gh-conf/gh-conf-constants/LICENSE)
```

**Comment by djovercash** [comment]
May I do this ticket?

**Comment by arshadkazmi42** [comment]
Yes go ahead

**Comment by djovercash** [comment]
Wonderful! Is there a specific position you would like the badge to appear, or just append to the end of the other badges? Also, it appears I do not have permissions just yet to push my branch up, so please let me know when I may do so.

Thanks for letting me do this ticket!

**Comment by arshadkazmi42** [comment]
You can follow the contributing guide
https://github.com/gh-conf/gh-conf-constants/blob/master/CONTRIBUTING.md

**Comment by arshadkazmi42** [comment]
We don't have any specific position in mind, feel free to place it wherever you feel suitable

**Comment by arshadkazmi42** [comment]
You must have cloned this repository. You should clone your forked repo. 
To fix this follow the below steps
1. Go to gh-conf-constants directory where you have cloned it.
2. vi `.git/config`
3. in that file, change `gh-conf` to your github username.

Then try pushing it.
Once its pushed. Open https://github.com/gh-conf/gh-conf-constants
And click on create pull request

**Comment by djovercash** [comment]
Oh I'm so sorry. Still drinking my morning coffee. 

Thanks for your help. PR is up: https://github.com/gh-conf/gh-conf-constants/pull/11

**Comment by arshadkazmi42** [comment]
@djovercash PR is merged. Thanks
