### ISSUE TITLE
NPM Downloads badge

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#7]
Add npm downloads badge with other badges in readme

```
[![NPM Downloads](https://img.shields.io/npm/dt/@gh-conf/gh-conf-constants.svg)](https://www.npmjs.com/package/@gh-conf/gh-conf-constants)
```

**Comment by djovercash** [comment]
May I do this ticket?

**Comment by arshadkazmi42** [comment]
Yes. you can do 1 first-timers-only issue.
Its limited to 1 issue per contributor so as to onboard more contributors

**Comment by djovercash** [comment]
Ah! Gotcha. Then I'll just do the License badge. Thanks!

**Comment by samplek** [comment]
Can I take this on @arshadkazmi42 ?

**Comment by arshadkazmi42** [comment]
Yes go ahead create a PR
