### ISSUE TITLE
NPM Version Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [gh-conf/gh-conf-constants#8]
NPM version badge with other badges in readme

```
[![NPM Version](https://img.shields.io/npm/v/@gh-conf/gh-conf-constants.svg)](https://www.npmjs.com/package/@gh-conf/gh-conf-constants)
```

**Comment by djovercash** [comment]
May I do this ticket?

**Comment by arshadkazmi42** [comment]
Yes. you can do 1 first-timers-only issue.
Its limited to 1 issue per contributor so as to onboard more contributors

**Comment by djovercash** [comment]
Ah! Gotcha. Then I'll just do the License badge. Thanks!

**Comment by mshah12** [comment]
Hi, can I take this issue?

**Comment by arshadkazmi42** [comment]
Yes

**Comment by mshah12** [comment]
Thanks. Created a pull request #13.
